source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', :group => :development
gem 'pg'
gem 'thin'

gem 'will_paginate'
gem 'jquery-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

gem 'debugger'
#gem 'ruby-debug19', :require => 'ruby-debug'

gem 'hobo', :git => 'git://github.com/tablatom/hobo'
gem 'rspec-rails', '>= 2.5.0', :group => [:test, :development]
gem 'shoulda', :group => :test
gem 'factory_girl', :group => :test
gem 'hobo_rapid', :git => 'git://github.com/tablatom/hobo'
gem 'hobo_jquery', :git => 'git://github.com/tablatom/hobo'
gem 'hobo_jquery_ui', :git => 'git://github.com/tablatom/hobo'
gem 'hobo_clean', :git => 'git://github.com/tablatom/hobo'
gem 'jquery-ui-themes', '~> 0.0.4'
gem 'hobo_clean_admin', :git => 'git://github.com/tablatom/hobo'
# The asset pipeline in Rails is really slow in development mode.
# Hobo has a lot of assets, so speed it up with rails-dev-tweaks

gem 'rails-dev-tweaks', '~> 0.6.1', :group => :development




